name: DrSleep
version: ${project.version}
main: org.acornmc.drsleep.DrSleep
api-version: 1.13
authors: [DrBot]
description: A fair sleeping solution
commands:
  phantom:
    description: adds you to the phantom list
    usage: /<command>
    permission: drsleep.phantom
  nosleep:
    description: adds you to the nosleep list
    usage: /<command>
    permission: drsleep.nosleep
  drsleep:
    description: DrSleep admin commands
    usage: /<command> <reload|clear|list>
    permission: drsleep.admin
permissions:
  drsleep.phantom:
    description: use the phantom command
    default: false
  drsleep.nosleep:
    description: use the nosleep command
    default: false
  drsleep.list:
    description: list the players on nosleep
    default: op
    children:
      - drsleep.admin
  drsleep.clear:
    description: clears the drsleep list
    default: op
    children:
      - drsleep.admin
  drsleep.reload:
    description: reloads DrSleep
    default: op
    children:
      - drsleep.admin